package name.velikodniy.jcexpress.sm;

import name.velikodniy.jcexpress.Hex;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

/**
 * Secure Messaging test vectors loaded from {@code src/test/resources/icao-sm-vectors/*.properties}.
 *
 * <p>The files are generated by {@code src/test/python/icao_ref.py}, an independent reference
 * implementation written from ICAO Doc 9303 Part 11 (sections 9.8.2-9.8.7, Figures 5 and 6) and
 * ISO/IEC 7816-4 (5.1 command APDU cases, 5.4.1 class byte). Its self-test reproduces every value of
 * the ICAO worked examples (App. D.2-D.4 and G.1) before any vector is written. The vectors were also
 * cross-checked, as a black box and outside the build, against JMRTD 0.8.8.</p>
 *
 * @param encKey session encryption key KSEnc
 * @param macKey session MAC key KSMAC
 * @param steps  protected exchanges in file order (each step records the SSC before its command)
 */
record SmVectors(byte[] encKey, byte[] macKey, List<Step> steps) {

    /**
     * One protected command/response exchange.
     *
     * @param name     human-readable description
     * @param ssc      SSC before the command is generated (ICAO 9303-11 9.8.2)
     * @param plain    unprotected command APDU
     * @param command  protected command APDU
     * @param response protected response APDU (data field and trailer)
     * @param data     unprotected response data
     * @param sw       status word carried in DO'99'
     * @param plainCla original CLA for the class-byte vectors, or -1
     */
    record Step(String name, byte[] ssc, byte[] plain, byte[] command, byte[] response, byte[] data,
                int sw, int plainCla) {

        @Override
        public String toString() {
            return name;
        }
    }

    /**
     * Loads a vector file from the test class path.
     *
     * @param file file name inside {@code icao-sm-vectors/}
     * @return the parsed vectors
     */
    static SmVectors load(String file) {
        Properties p = new Properties();
        try (InputStream in = SmVectors.class.getResourceAsStream("/icao-sm-vectors/" + file)) {
            if (in == null) {
                throw new IllegalStateException("Missing test vector file " + file);
            }
            p.load(in);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        List<Step> steps = new ArrayList<>();
        int count = Integer.parseInt(p.getProperty("steps"));
        for (int i = 0; i < count; i++) {
            steps.add(step(p, i + "."));
        }
        return new SmVectors(hex(p, "keys.enc"), hex(p, "keys.mac"), List.copyOf(steps));
    }

    /**
     * Creates a fresh SM context positioned at the SSC recorded for the given step.
     *
     * @param algorithm the algorithm suite of the vector file
     * @param step      the step whose SSC is used
     * @return a new context
     */
    SMContext context(SMAlgorithm algorithm, Step step) {
        return new SMContext(algorithm, new SMKeys(encKey, macKey), step.ssc());
    }

    /**
     * Returns the step at the given index.
     *
     * @param index zero-based step index
     * @return the step
     */
    Step step(int index) {
        return steps.get(index);
    }

    private static Step step(Properties p, String prefix) {
        String cla = p.getProperty(prefix + "plainCla");
        return new Step(p.getProperty(prefix + "name"), hex(p, prefix + "ssc"), hex(p, prefix + "plain"),
                hex(p, prefix + "command"), hex(p, prefix + "response"), hex(p, prefix + "data"),
                Integer.parseInt(p.getProperty(prefix + "sw"), 16),
                cla == null ? -1 : Integer.parseInt(cla, 16));
    }

    private static byte[] hex(Properties p, String key) {
        String value = p.getProperty(key);
        if (value == null) {
            throw new IllegalStateException("Missing vector property " + key);
        }
        return Hex.decode(value);
    }
}
