package name.velikodniy.jcexpress.pace;

import name.velikodniy.jcexpress.crypto.CryptoUtil;

import java.math.BigInteger;
import java.security.KeyPair;
import java.security.SecureRandom;
import java.security.interfaces.ECPrivateKey;
import java.security.spec.ECFieldFp;
import java.security.spec.ECParameterSpec;
import java.security.spec.ECPoint;
import java.security.spec.EllipticCurve;
import java.util.Arrays;

/**
 * Low-level elliptic curve operations for PACE.
 *
 * <p>Provides EC point arithmetic (addition, scalar multiplication),
 * ECDH key agreement, Generic Mapping, and authentication token computation.</p>
 *
 * <p>Point arithmetic uses affine coordinates with BigInteger. This is not
 * side-channel resistant but is appropriate for a testing framework.</p>
 */
public final class PaceCrypto {

    private static final SecureRandom RANDOM = new SecureRandom();

    private PaceCrypto() {
    }

    /**
     * Decodes and validates an uncompressed EC point ({@code 0x04 || x || y}).
     *
     * <p>Received ephemeral public keys are validated as recommended by ICAO Doc 9303-11, 9.4.5 and Table 13
     * (BSI TR-03111 public key validation): both coordinates must be field elements ({@code 0 <= x, y < p}) and the
     * point must satisfy the curve equation. The uncompressed encoding cannot express the point at infinity, and
     * the cofactor of every standardized curve is 1, so such a point lies in the group generated by G.</p>
     *
     * @param encoded the encoded point bytes
     * @param curve   the elliptic curve
     * @return the decoded EC point
     * @throws PaceException if the encoding is invalid or the point is not on the curve
     */
    public static ECPoint decodePoint(byte[] encoded, EllipticCurve curve) {
        if (encoded.length == 0 || encoded[0] != 0x04) {
            throw new PaceException("Expected uncompressed EC point (0x04 prefix), got 0x"
                    + (encoded.length > 0 ? String.format("%02X", encoded[0] & 0xFF) : "empty"));
        }
        int fieldSize = fieldSize(curve);
        if (encoded.length != 1 + 2 * fieldSize) {
            throw new PaceException("Invalid EC point length: expected " + (1 + 2 * fieldSize)
                    + ", got " + encoded.length);
        }
        BigInteger x = new BigInteger(1, Arrays.copyOfRange(encoded, 1, 1 + fieldSize));
        BigInteger y = new BigInteger(1, Arrays.copyOfRange(encoded, 1 + fieldSize, encoded.length));
        ECPoint point = new ECPoint(x, y);
        validate(point, curve);
        return point;
    }

    /**
     * Checks that a point is a valid affine point of the curve (BSI TR-03111 public key validation).
     *
     * @param point the point
     * @param curve the curve
     * @throws PaceException if a coordinate is not a field element or the curve equation does not hold
     */
    static void validate(ECPoint point, EllipticCurve curve) {
        BigInteger p = ((ECFieldFp) curve.getField()).getP();
        BigInteger x = point.getAffineX();
        BigInteger y = point.getAffineY();
        if (x.compareTo(p) >= 0 || y.compareTo(p) >= 0) {
            throw new PaceException("EC point coordinate is not an element of the field");
        }
        BigInteger lhs = y.multiply(y).mod(p);
        BigInteger rhs = x.pow(3).add(curve.getA().multiply(x)).add(curve.getB()).mod(p);
        if (!lhs.equals(rhs)) {
            throw new PaceException("EC point is not on the curve (public key validation, BSI TR-03111)");
        }
    }

    /**
     * Encodes an EC point as uncompressed ({@code 0x04 || x || y}).
     *
     * @param point     the EC point
     * @param fieldSize the field size in bytes
     * @return the encoded point bytes
     */
    public static byte[] encodePoint(ECPoint point, int fieldSize) {
        byte[] encoded = new byte[1 + 2 * fieldSize];
        encoded[0] = 0x04;
        byte[] x = toFixedLength(point.getAffineX(), fieldSize);
        byte[] y = toFixedLength(point.getAffineY(), fieldSize);
        System.arraycopy(x, 0, encoded, 1, fieldSize);
        System.arraycopy(y, 0, encoded, 1 + fieldSize, fieldSize);
        return encoded;
    }

    /**
     * Adds two EC points on the given curve.
     *
     * @param p     first point
     * @param q     second point
     * @param curve the elliptic curve
     * @return P + Q
     */
    public static ECPoint pointAdd(ECPoint p, ECPoint q, EllipticCurve curve) {
        if (p.equals(ECPoint.POINT_INFINITY)) return q;
        if (q.equals(ECPoint.POINT_INFINITY)) return p;

        BigInteger prime = ((ECFieldFp) curve.getField()).getP();
        BigInteger px = p.getAffineX();
        BigInteger py = p.getAffineY();
        BigInteger qx = q.getAffineX();
        BigInteger qy = q.getAffineY();

        BigInteger lambda;
        if (px.equals(qx)) {
            if (py.equals(qy)) {
                // Point doubling: lambda = (3*x^2 + a) / (2*y) mod p
                BigInteger num = px.modPow(BigInteger.TWO, prime)
                        .multiply(BigInteger.valueOf(3))
                        .add(curve.getA())
                        .mod(prime);
                BigInteger den = py.multiply(BigInteger.TWO).modInverse(prime);
                lambda = num.multiply(den).mod(prime);
            } else {
                // P + (-P) = infinity
                return ECPoint.POINT_INFINITY;
            }
        } else {
            // lambda = (qy - py) / (qx - px) mod p
            BigInteger num = qy.subtract(py).mod(prime);
            BigInteger den = qx.subtract(px).modInverse(prime);
            lambda = num.multiply(den).mod(prime);
        }

        // rx = lambda^2 - px - qx mod p
        BigInteger rx = lambda.modPow(BigInteger.TWO, prime)
                .subtract(px).subtract(qx).mod(prime);
        // ry = lambda * (px - rx) - py mod p
        BigInteger ry = lambda.multiply(px.subtract(rx)).subtract(py).mod(prime);

        return new ECPoint(rx, ry);
    }

    /**
     * Computes scalar multiplication k * P using double-and-add.
     *
     * @param k     the scalar
     * @param p     the EC point
     * @param curve the elliptic curve
     * @return k * P
     */
    public static ECPoint scalarMultiply(BigInteger k, ECPoint p, EllipticCurve curve) {
        if (k.signum() == 0 || p.equals(ECPoint.POINT_INFINITY)) {
            return ECPoint.POINT_INFINITY;
        }
        // Reduce k modulo the curve order if needed (caller should ensure positive k)
        ECPoint result = ECPoint.POINT_INFINITY;
        ECPoint addend = p;

        BigInteger scalar = k;
        while (scalar.signum() > 0) {
            if (scalar.testBit(0)) {
                result = pointAdd(result, addend, curve);
            }
            addend = pointAdd(addend, addend, curve);
            scalar = scalar.shiftRight(1);
        }
        return result;
    }

    /**
     * Performs the elliptic-curve Diffie-Hellman key agreement ECKA of BSI TR-03111 (ICAO Doc 9303-11, 9.6).
     *
     * <p>Returns the x-coordinate of {@code privateKey * publicPoint} as an octet string of the field size, which is
     * the shared secret K for the KDF (ICAO Doc 9303-11, 9.7.1 Note). The cofactor of all standardized curves is 1.</p>
     *
     * @param privateKey  the local private key
     * @param publicPoint the remote public point
     * @param params      the EC parameters
     * @return the shared secret (x-coordinate of the shared point)
     * @throws PaceException if the shared point is the point at infinity
     */
    public static byte[] ecdh(ECPrivateKey privateKey, ECPoint publicPoint, ECParameterSpec params) {
        return sharedSecret(privateKey.getS(), publicPoint, params);
    }

    static byte[] sharedSecret(BigInteger privateKey, ECPoint publicPoint, ECParameterSpec params) {
        ECPoint sharedPoint = scalarMultiply(privateKey, publicPoint, params.getCurve());
        if (sharedPoint.equals(ECPoint.POINT_INFINITY)) {
            throw new PaceException("ECDH key agreement produced the point at infinity");
        }
        return toFixedLength(sharedPoint.getAffineX(), fieldSize(params.getCurve()));
    }

    /**
     * Generates a random EC key pair on the given domain parameters.
     *
     * <p>The key pair is generated without the JCA provider (see {@link #generateKeyPairOnGenerator}), so it works
     * for every curve of ICAO Doc 9303-11 Table 12, including the Brainpool curves that the JDK no longer
     * supports.</p>
     *
     * @param params the EC parameters
     * @return the generated key pair
     */
    public static KeyPair generateKeyPair(ECParameterSpec params) {
        return generateKeyPairOnGenerator(params.getGenerator(), params);
    }

    /**
     * Generates a key pair on a custom generator, e.g. the mapped generator G^ of PACE (ICAO Doc 9303-11,
     * 4.4.1 step 3c).
     *
     * <p>The private key is a uniformly random scalar {@code 1 <= k < n} (see {@link #randomScalar}); the public
     * key is {@code k * generator}.</p>
     *
     * @param generator the generator point
     * @param params    the EC parameters (curve and order n)
     * @return a key pair whose public point is {@code k * generator}
     */
    public static KeyPair generateKeyPairOnGenerator(ECPoint generator, ECParameterSpec params) {
        return keyPair(randomScalar(params.getOrder(), RANDOM), generator, params);
    }

    /**
     * Builds the key pair for a given private scalar.
     *
     * @param privateKey the private scalar
     * @param generator  the generator point
     * @param params     the EC parameters
     * @return the key pair {@code (k * generator, k)}
     */
    static KeyPair keyPair(BigInteger privateKey, ECPoint generator, ECParameterSpec params) {
        ECPoint publicPoint = scalarMultiply(privateKey, generator, params.getCurve());
        return new KeyPair(new EcKeys.PublicKey(publicPoint, params), new EcKeys.PrivateKey(privateKey, params));
    }

    /**
     * Draws a uniformly distributed scalar {@code 1 <= k < order}.
     *
     * <p>Uses the "extra random bits" method of FIPS 186-4 B.4.1: {@code k = (c mod (n - 1)) + 1} where c has
     * {@code bitlen(n) + 64} random bits, which makes the bias negligible.</p>
     *
     * @param order  the group order n
     * @param random the random source
     * @return the scalar
     */
    static BigInteger randomScalar(BigInteger order, SecureRandom random) {
        BigInteger c = new BigInteger(order.bitLength() + 64, random);
        return c.mod(order.subtract(BigInteger.ONE)).add(BigInteger.ONE);
    }

    /**
     * Performs Generic Mapping: G' = s * G + H.
     *
     * <p>Where s is the decrypted nonce, G is the base generator,
     * and H is the ECDH shared point from the mapping step.</p>
     *
     * @param nonce       the decrypted nonce as BigInteger
     * @param generator   the base generator G
     * @param sharedPoint the ECDH shared point H
     * @param curve       the elliptic curve
     * @return the mapped generator G'
     */
    public static ECPoint genericMapping(BigInteger nonce, ECPoint generator,
                                          ECPoint sharedPoint, EllipticCurve curve) {
        ECPoint sG = scalarMultiply(nonce, generator, curve);
        return pointAdd(sG, sharedPoint, curve);
    }

    /**
     * Maps the PACE nonce to the ephemeral generator with the ECDH Generic Mapping (ICAO Doc 9303-11, 4.4.3.3.1).
     *
     * <p>{@code G^ = s * G + H}, where {@code H = KA(SK_Map,IFD, PK_Map,IC) = SK_Map,IFD * PK_Map,IC} is the full
     * Diffie-Hellman point (not its x-coordinate).</p>
     *
     * @param nonce                the decrypted nonce s
     * @param mappingPrivateKey    the terminal's mapping private key SK_Map,IFD
     * @param chipMappingPublicKey the chip's mapping public key PK_Map,IC
     * @param params               the static domain parameters (generator G)
     * @return the mapped generator G^
     * @throws PaceException if H or G^ is the point at infinity
     */
    public static ECPoint mapNonceGeneric(BigInteger nonce, BigInteger mappingPrivateKey,
                                          ECPoint chipMappingPublicKey, ECParameterSpec params) {
        EllipticCurve curve = params.getCurve();
        ECPoint h = scalarMultiply(mappingPrivateKey, chipMappingPublicKey, curve);
        if (h.equals(ECPoint.POINT_INFINITY)) {
            throw new PaceException("Generic Mapping: the shared point H is the point at infinity");
        }
        ECPoint mapped = genericMapping(nonce, params.getGenerator(), h, curve);
        if (mapped.equals(ECPoint.POINT_INFINITY)) {
            throw new PaceException("Generic Mapping: the mapped generator is the point at infinity");
        }
        return mapped;
    }

    /**
     * Computes the PACE authentication token.
     *
     * <p>token = AES-CMAC(K_mac, OID || publicKey), truncated to 8 bytes.</p>
     *
     * @param macKey          the MAC key
     * @param oidBytes        the DER-encoded OID bytes
     * @param publicKeyEncoded the encoded public key point (uncompressed)
     * @return 8-byte authentication token
     */
    public static byte[] authToken(byte[] macKey, byte[] oidBytes, byte[] publicKeyEncoded) {
        // Build the MAC input: 7F49 [L] (06 [L] OID || 86 [L] pubKey)
        // This is the ephemeral public key info per BSI TR-03110
        byte[] oidTlv = buildTlv(0x06, oidBytes);
        byte[] pkTlv = buildTlv(0x86, publicKeyEncoded);

        byte[] innerData = new byte[oidTlv.length + pkTlv.length];
        System.arraycopy(oidTlv, 0, innerData, 0, oidTlv.length);
        System.arraycopy(pkTlv, 0, innerData, oidTlv.length, pkTlv.length);

        byte[] macInput = buildTlv(0x7F49, innerData);

        byte[] fullMac = CryptoUtil.aesCmac(macKey, macInput);
        return Arrays.copyOf(fullMac, 8);
    }

    /**
     * Returns the field size in bytes for the given curve.
     *
     * @param curve the elliptic curve
     * @return field size in bytes
     */
    public static int fieldSize(EllipticCurve curve) {
        return (((ECFieldFp) curve.getField()).getP().bitLength() + 7) / 8;
    }

    /**
     * Converts a BigInteger to a fixed-length unsigned byte array.
     */
    static byte[] toFixedLength(BigInteger value, int length) {
        byte[] bytes = value.toByteArray();
        if (bytes.length == length) {
            return bytes;
        }
        if (bytes.length > length) {
            // Strip leading zero byte(s)
            return Arrays.copyOfRange(bytes, bytes.length - length, bytes.length);
        }
        // Pad with leading zeros
        byte[] padded = new byte[length];
        System.arraycopy(bytes, 0, padded, length - bytes.length, bytes.length);
        return padded;
    }

    /**
     * Builds a simple TLV (tag + BER length + value).
     */
    private static byte[] buildTlv(int tag, byte[] value) {
        java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
        // Write tag
        if (tag > 0xFFFF) {
            out.write((tag >> 16) & 0xFF);
            out.write((tag >> 8) & 0xFF);
            out.write(tag & 0xFF);
        } else if (tag > 0xFF) {
            out.write((tag >> 8) & 0xFF);
            out.write(tag & 0xFF);
        } else {
            out.write(tag & 0xFF);
        }
        // Write BER length
        if (value.length <= 0x7F) {
            out.write(value.length);
        } else if (value.length <= 0xFF) {
            out.write(0x81);
            out.write(value.length);
        } else {
            out.write(0x82);
            out.write((value.length >> 8) & 0xFF);
            out.write(value.length & 0xFF);
        }
        out.writeBytes(value);
        return out.toByteArray();
    }
}
