package name.velikodniy.jcexpress.plugin.testing;

import name.velikodniy.jcexpress.plugin.JavaCardBuildMojo;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilderFactory;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;

/**
 * The plugin descriptor ({@code META-INF/maven/plugin.xml}) generated by maven-plugin-plugin
 * from the Mojo annotations. It is what Maven uses to map {@code <configuration>} elements and
 * user properties to Mojo fields, so tests read the documented contract from here.
 */
public final class PluginDescriptor {

    private final Element mojo;
    private final Map<String, Parameter> parameters = new LinkedHashMap<>();

    private PluginDescriptor(Element mojo) {
        this.mojo = mojo;
        NodeList params = ((Element) mojo.getElementsByTagName("parameters").item(0))
                .getElementsByTagName("parameter");
        Element configuration = (Element) mojo.getElementsByTagName("configuration").item(0);
        for (int i = 0; i < params.getLength(); i++) {
            Element p = (Element) params.item(i);
            String name = text(p, "name").orElseThrow();
            Element config = child(configuration, name);
            parameters.put(name, new Parameter(name, text(p, "alias").orElse(null),
                    text(p, "type").orElseThrow(), text(p, "deprecated").orElse(null),
                    "false".equals(text(p, "editable").orElse("true")),
                    config == null ? null : config.getTextContent().trim(),
                    config == null || !config.hasAttribute("default-value") ? null : config.getAttribute("default-value")));
        }
    }

    /** @return the descriptor of the {@code build} goal */
    public static PluginDescriptor buildGoal() {
        try (InputStream in = Files.newInputStream(descriptorPath())) {
            Document doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(in);
            NodeList mojos = doc.getElementsByTagName("mojo");
            for (int i = 0; i < mojos.getLength(); i++) {
                Element m = (Element) mojos.item(i);
                if ("build".equals(text(m, "goal").orElse(""))) {
                    return new PluginDescriptor(m);
                }
            }
            throw new IllegalStateException("goal 'build' not found in plugin.xml");
        } catch (Exception e) {
            throw new IllegalStateException("Cannot read plugin descriptor", e);
        }
    }

    /**
     * Returns a plugin-level descriptor element such as {@code requiredMavenVersion}.
     *
     * @param element element name
     * @return its text, if present
     */
    public static Optional<String> pluginElement(String element) {
        try (InputStream in = Files.newInputStream(descriptorPath())) {
            Document doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(in);
            return text(doc.getDocumentElement(), element);
        } catch (Exception e) {
            throw new IllegalStateException("Cannot read plugin descriptor", e);
        }
    }

    /**
     * Finds a parameter by its name or alias, the way Maven matches configuration elements.
     *
     * @param nameOrAlias configuration element name
     * @return the parameter, if declared
     */
    public Optional<Parameter> parameter(String nameOrAlias) {
        Parameter direct = parameters.get(nameOrAlias);
        if (direct != null) {
            return Optional.of(direct);
        }
        return parameters.values().stream().filter(p -> nameOrAlias.equals(p.alias())).findFirst();
    }

    /** @return all parameters by name */
    public Map<String, Parameter> parameters() {
        return Map.copyOf(parameters);
    }

    /**
     * Returns a mojo-level descriptor element such as {@code phase} or {@code threadSafe}.
     *
     * @param element element name
     * @return its text, if present
     */
    public Optional<String> mojoElement(String element) {
        return text(mojo, element);
    }

    private static Path descriptorPath() throws URISyntaxException {
        Path classes = Path.of(JavaCardBuildMojo.class.getProtectionDomain().getCodeSource().getLocation().toURI());
        return classes.resolve("META-INF/maven/plugin.xml");
    }

    private static Optional<String> text(Element parent, String name) {
        Element e = child(parent, name);
        return e == null ? Optional.empty() : Optional.of(e.getTextContent().trim());
    }

    private static Element child(Element parent, String name) {
        for (Node n = parent.getFirstChild(); n != null; n = n.getNextSibling()) {
            if (n instanceof Element e && e.getTagName().equals(name)) {
                return e;
            }
        }
        return null;
    }

    /**
     * A Mojo parameter as declared in plugin.xml.
     *
     * @param name         field / configuration element name
     * @param alias        alternative configuration element name, or {@code null}
     * @param type         Java type
     * @param deprecated   deprecation text, or {@code null}
     * @param readonly     {@code true} if users may not configure it
     * @param expression   the configuration expression, e.g. {@code ${javacard.version}}
     * @param defaultValue the default value expression, or {@code null}
     */
    public record Parameter(String name, String alias, String type, String deprecated, boolean readonly,
                            String expression, String defaultValue) {

        /** @return the user property bound to this parameter, e.g. {@code javacard.version} */
        public Optional<String> property() {
            if (expression != null && expression.startsWith("${") && expression.endsWith("}")) {
                return Optional.of(expression.substring(2, expression.length() - 1));
            }
            return Optional.empty();
        }
    }
}
