package name.velikodniy.jcexpress.gp;

import name.velikodniy.jcexpress.Hex;
import name.velikodniy.jcexpress.scp.SCPKeys;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * A known-answer SCP02/SCP03 session transcript loaded from a test resource.
 *
 * <p>The resources {@code scp-spec-vectors.txt}, {@code scp-boundary-vectors.txt},
 * {@code scp-error-status-vectors.txt}, {@code scp-transport-vectors.txt} and {@code scp-public-transcripts.txt}
 * are NOT produced by javacard-express: the first two were generated by an independent reference implementation
 * written from GlobalPlatform Card Specification v2.3.1 Appendix E (SCP02) and Amendment D (SCP03), the boundary
 * vectors with command and response lengths around the padding boundaries and the per-level maximum; the error
 * status and transport vectors by a second independent reference (the protocols review's), cross-checked with
 * the first one, with error status words between protected responses resp. '6CXX' and '61XX' answers (the
 * transport file lists wire exchanges, see its header, and is not part of {@link #all()}); the last one contains
 * public transcripts of real cards and of third-party implementations (see the SOURCE line of each case).
 * Format, one case per block:</p>
 * <pre>
 * CASE name
 * SOURCE provenance                         (optional)
 * PROTO 2|3
 * OPTION i                                  (SCP02 only: implementation option of the host)
 * KVN kvn                                   (INITIALIZE UPDATE P1)
 * KEYS enc mac dek
 * HOST host-challenge
 * LEVEL security-level
 * IU INITIALIZE-UPDATE-response-data
 * EA EXTERNAL-AUTHENTICATE-command
 * CMD plain wrapped raw-card-response expected-data|- expected-SW
 * END
 * </pre>
 *
 * @param name          case name
 * @param source        provenance, or empty
 * @param protocol      2 or 3
 * @param option        SCP02 implementation option "i", or -1
 * @param keyVersion    the INITIALIZE UPDATE P1
 * @param enc           static ENC key
 * @param mac           static MAC key
 * @param dek           static DEK key
 * @param hostChallenge the host challenge
 * @param level         the security level
 * @param initUpdate    the INITIALIZE UPDATE response data (without SW)
 * @param extAuth       the expected EXTERNAL AUTHENTICATE command
 * @param commands      the commands of the session
 */
public record ScpTranscript(String name, String source, int protocol, int option, int keyVersion,
                            byte[] enc, byte[] mac, byte[] dek, byte[] hostChallenge, int level,
                            byte[] initUpdate, byte[] extAuth, List<Command> commands) {

    /** Spec-derived vectors (independent reference implementation). */
    public static final String SPEC_VECTORS = "scp-spec-vectors.txt";

    /** Spec-derived boundary vectors: lengths around the padding boundaries and the per-level maximum. */
    public static final String BOUNDARY_VECTORS = "scp-boundary-vectors.txt";

    /**
     * Spec-derived vectors with error status words between protected responses: SCP02 R-MAC sessions where the
     * card answers errors with the bare status word (GPCS v2.3.1 E.4.5, ISO/IEC 7816-4:2005 5.1.3) and SCP03
     * sessions whose errors carry no R-MAC (Amendment D 6.2.5).
     */
    public static final String ERROR_STATUS_VECTORS = "scp-error-status-vectors.txt";

    /**
     * Spec-derived '6CXX' and '61XX' scenarios under a secure channel (ISO/IEC 7816-4:2005 5.1.3, GPCS v2.3.1
     * 11.1.5.2). Its CMD lines are wire exchanges (see the file header), so it is not part of {@link #all()}.
     */
    public static final String TRANSPORT_VECTORS = "scp-transport-vectors.txt";

    /** Public real-card and third-party transcripts. */
    public static final String PUBLIC_TRANSCRIPTS = "scp-public-transcripts.txt";

    /**
     * One command of a transcript.
     *
     * @param plain        the command before secure messaging
     * @param wrapped      the command on the wire
     * @param cardResponse the card response on the wire (data, MAC and SW)
     * @param data         the expected response data after unwrapping
     * @param sw           the expected status word
     */
    public record Command(byte[] plain, byte[] wrapped, byte[] cardResponse, byte[] data, int sw) {
        @Override
        public String toString() {
            return Hex.encode(plain);
        }
    }

    /**
     * Returns the static keys of this transcript.
     *
     * @return the key set
     */
    public SCPKeys keys() {
        return SCPKeys.of(enc, mac, dek);
    }

    /**
     * Returns the INITIALIZE UPDATE command the host must send (Le '00', GPCS Table E-7 / Amd D Table 7-2).
     *
     * @return the expected INITIALIZE UPDATE command
     */
    public byte[] initUpdateCommand() {
        byte[] apdu = new byte[6 + hostChallenge.length];
        apdu[0] = (byte) 0x80;
        apdu[1] = 0x50;
        apdu[2] = (byte) keyVersion;
        apdu[4] = (byte) hostChallenge.length;
        System.arraycopy(hostChallenge, 0, apdu, 5, hostChallenge.length);
        return apdu;
    }

    @Override
    public String toString() {
        return name;
    }

    /**
     * Loads all transcripts of a resource file.
     *
     * @param resource {@link #SPEC_VECTORS}, {@link #BOUNDARY_VECTORS}, {@link #ERROR_STATUS_VECTORS},
     *                 {@link #TRANSPORT_VECTORS} or {@link #PUBLIC_TRANSCRIPTS}
     * @return the transcripts in file order
     */
    public static List<ScpTranscript> load(String resource) {
        try (InputStream in = ScpTranscript.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("Missing test resource " + resource);
            }
            return parse(new String(in.readAllBytes(), StandardCharsets.US_ASCII));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * Loads all transcripts whose CMD lines are host commands (every resource file but
     * {@link #TRANSPORT_VECTORS}).
     *
     * @return spec-derived, boundary and error status vectors followed by public transcripts
     */
    public static List<ScpTranscript> all() {
        List<ScpTranscript> all = new ArrayList<>(load(SPEC_VECTORS));
        all.addAll(load(BOUNDARY_VECTORS));
        all.addAll(load(ERROR_STATUS_VECTORS));
        all.addAll(load(PUBLIC_TRANSCRIPTS));
        return all;
    }

    /**
     * Finds a transcript by name in the resource files of {@link #all()}.
     *
     * @param name the case name
     * @return the transcript
     */
    public static ScpTranscript named(String name) {
        return all().stream().filter(t -> t.name().equals(name)).findFirst()
                .orElseThrow(() -> new IllegalArgumentException("No transcript " + name));
    }

    private static List<ScpTranscript> parse(String text) {
        List<ScpTranscript> result = new ArrayList<>();
        Builder b = null;
        for (String line : text.split("\n")) {
            String[] t = line.trim().split("\\s+", 2);
            if (t[0].isEmpty() || t[0].startsWith("#")) {
                continue;
            }
            if (t[0].equals("CASE")) {
                b = new Builder(t[1]);
            } else if (t[0].equals("END")) {
                result.add(b.build());
            } else {
                b.accept(t[0], t[1]);
            }
        }
        return result;
    }

    private static final class Builder {
        private final String name;
        private final List<Command> commands = new ArrayList<>();
        private String source = "";
        private int protocol;
        private int option = -1;
        private int keyVersion;
        private byte[][] keys;
        private byte[] host;
        private int level;
        private byte[] initUpdate;
        private byte[] extAuth;

        Builder(String name) {
            this.name = name;
        }

        void accept(String key, String value) {
            switch (key) {
                case "SOURCE" -> source = value;
                case "PROTO" -> protocol = Integer.parseInt(value);
                case "OPTION" -> option = Integer.parseInt(value, 16);
                case "KVN" -> keyVersion = Integer.parseInt(value, 16);
                case "KEYS" -> keys = splitHex(value);
                case "HOST" -> host = Hex.decode(value);
                case "LEVEL" -> level = Integer.parseInt(value, 16);
                case "IU" -> initUpdate = Hex.decode(value);
                case "EA" -> extAuth = Hex.decode(value);
                case "CMD" -> commands.add(command(value.split("\\s+")));
                default -> throw new IllegalArgumentException("Unknown transcript line " + key);
            }
        }

        private static Command command(String[] f) {
            byte[] data = f[3].equals("-") ? new byte[0] : Hex.decode(f[3]);
            return new Command(Hex.decode(f[0]), Hex.decode(f[1]), Hex.decode(f[2]), data,
                    Integer.parseInt(f[4], 16));
        }

        private static byte[][] splitHex(String value) {
            String[] parts = value.split("\\s+");
            return new byte[][]{Hex.decode(parts[0]), Hex.decode(parts[1]), Hex.decode(parts[2])};
        }

        ScpTranscript build() {
            return new ScpTranscript(name, source, protocol, option, keyVersion, keys[0], keys[1], keys[2],
                    host, level, initUpdate, extAuth, List.copyOf(commands));
        }
    }
}
