package name.velikodniy.jcexpress.converter;

import java.util.Arrays;
import java.util.HexFormat;
import java.util.List;
import java.util.Objects;

/**
 * Result of a successful CAP file conversion, produced by {@link Converter#convert()}.
 *
 * <p>Contains the binary artifacts generated by the conversion pipeline:
 * <ul>
 *   <li>A <b>CAP file</b> -- the deployable JavaCard package in JAR/ZIP format, containing
 *       all required components as defined by JCVM spec Chapter 6 (Header, Directory,
 *       Import, ConstantPool, Class, Method, StaticField, ReferenceLocation, Descriptor,
 *       and optionally Applet and Export).</li>
 *   <li>An <b>export file</b> ({@code .exp}, JCVM 3.1 Chapter 5) -- the package's public API
 *       with its tokens, enabling other packages to import and link against this package. It is
 *       generated for every conversion: a library package describes all its public classes and
 *       interfaces, a package with applets only its public shareable interfaces (§5.5).</li>
 * </ul>
 *
 * <p>The {@link #warnings()} list may contain non-fatal messages about potential issues
 * detected during conversion (e.g., a package AID generated from the package name, or a
 * package AID equal to the AID of another known package). An empty list indicates a clean
 * conversion.
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * ConverterResult result = converter.convert();
 *
 * // Write CAP file to disk
 * Files.write(Path.of("output.cap"), result.capFile());
 *
 * // Write the export file where an export path finds it: <package>/javacard/<last name>.exp
 * // (JCVM 3.1 §4.1.1, §5.2), e.g. for package com.example
 * Path exp = Files.createDirectories(Path.of("exports/com/example/javacard")).resolve("example.exp");
 * Files.write(exp, result.exportFile());
 *
 * System.out.println("CAP size: " + result.capSize() + " bytes");
 * result.warnings().forEach(w -> System.err.println("WARN: " + w));
 * }</pre>
 *
 * @param capFile    complete CAP file bytes in JAR/ZIP format, ready to be loaded onto a card
 * @param exportFile binary export ({@code .exp}) file bytes for use by other packages
 *                   that import this package
 * @param warnings   non-fatal warnings generated during conversion; empty list if none
 * @param capSize    size of the CAP file in bytes (equivalent to {@code capFile.length})
 *
 * @see Converter#convert()
 * @see ConverterException
 */
public record ConverterResult(
        byte[] capFile,
        byte[] exportFile,
        List<String> warnings,
        int capSize
) {
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof ConverterResult(var cf, var ef, var w, var cs)) {
            return capSize == cs
                    && Arrays.equals(capFile, cf)
                    && Arrays.equals(exportFile, ef)
                    && Objects.equals(warnings, w);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return 31 * (31 * Arrays.hashCode(capFile) + Arrays.hashCode(exportFile))
                + Objects.hashCode(warnings);
    }

    @Override
    public String toString() {
        var hex = HexFormat.of();
        return "ConverterResult[capFile=" + hex.formatHex(capFile)
                + ", exportFile=" + hex.formatHex(exportFile)
                + ", warnings=" + warnings
                + ", capSize=" + capSize + "]";
    }
}
