package name.velikodniy.jcexpress.converter;

import java.util.Arrays;
import java.util.HexFormat;
import java.util.List;
import java.util.Objects;

/**
 * Result of a successful CAP file conversion, produced by {@link Converter#convert()}.
 *
 * <p>Contains the binary artifacts generated by the conversion pipeline:
 * <ul>
 *   <li>A <b>CAP file</b> -- the deployable JavaCard package in JAR/ZIP format, containing
 *       all required components as defined by JCVM spec Chapter 6 (Header, Directory,
 *       Import, ConstantPool, Class, Method, StaticField, ReferenceLocation, Descriptor,
 *       and optionally Applet and Export).</li>
 *   <li>An <b>export file</b> ({@code .exp}) -- a binary file describing the package's
 *       public API tokens, enabling other packages to import and link against this package.</li>
 * </ul>
 *
 * <p>The {@link #warnings()} list may contain non-fatal messages about potential issues
 * detected during conversion (e.g., unused imports, missing optional metadata). An empty
 * list indicates a clean conversion.
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * ConverterResult result = converter.convert();
 *
 * // Write CAP file to disk
 * Files.write(Path.of("output.cap"), result.capFile());
 *
 * // Write export file for downstream packages
 * Files.write(Path.of("output.exp"), result.exportFile());
 *
 * System.out.println("CAP size: " + result.capSize() + " bytes");
 * result.warnings().forEach(w -> System.err.println("WARN: " + w));
 * }</pre>
 *
 * @param capFile    complete CAP file bytes in JAR/ZIP format, ready to be loaded onto a card
 * @param exportFile binary export ({@code .exp}) file bytes for use by other packages
 *                   that import this package
 * @param warnings   non-fatal warnings generated during conversion; empty list if none
 * @param capSize    size of the CAP file in bytes (equivalent to {@code capFile.length})
 *
 * @see Converter#convert()
 * @see ConverterException
 */
public record ConverterResult(
        byte[] capFile,
        byte[] exportFile,
        List<String> warnings,
        int capSize
) {
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof ConverterResult(var cf, var ef, var w, var cs)) {
            return capSize == cs
                    && Arrays.equals(capFile, cf)
                    && Arrays.equals(exportFile, ef)
                    && Objects.equals(warnings, w);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return 31 * (31 * Arrays.hashCode(capFile) + Arrays.hashCode(exportFile))
                + Objects.hashCode(warnings);
    }

    @Override
    public String toString() {
        var hex = HexFormat.of();
        return "ConverterResult[capFile=" + hex.formatHex(capFile)
                + ", exportFile=" + hex.formatHex(exportFile)
                + ", warnings=" + warnings
                + ", capSize=" + capSize + "]";
    }
}
