package javacard.security;

/**
 * The RandomData abstract class is the base class for random number generation.
 */
@SuppressWarnings({"java:S1172", "java:S112"}) // API stubs: params are contractual, RuntimeException is intentional
public abstract class RandomData {

    /**
     * Constructor for algorithm implementations; applets obtain instances through {@code getInstance}.
     */
    protected RandomData() {
        throw new RuntimeException("stub");
    }

    /** General-purpose pseudo-random generator. */
    public static final byte ALG_PSEUDO_RANDOM = 1;
    /** Cryptographically secure random generator. */
    public static final byte ALG_SECURE_RANDOM = 2;
    /** True random number generator backed by a physical entropy source. */
    public static final byte ALG_TRNG = 3;
    /** Deterministic random bit generator that the platform has already seeded. */
    public static final byte ALG_PRESEEDED_DRBG = 4;
    /** Fast generator for uses that do not need cryptographic strength (for example masking). */
    public static final byte ALG_FAST = 5;
    /** Generator suitable for producing key material. */
    public static final byte ALG_KEYGENERATION = 6;

    /**
     * Creates a RandomData instance for the specified algorithm.
     *
     * @param algorithm the algorithm type
     * @return the RandomData instance
     * @throws CryptoException with NO_SUCH_ALGORITHM if the requested algorithm is not supported
     */
    public static final RandomData getInstance(byte algorithm) throws CryptoException {
        throw new RuntimeException("stub");
    }

    /**
     * Generates random data.
     *
     * @param buffer output buffer
     * @param offset offset into the buffer
     * @param length number of bytes to generate
     * @throws CryptoException if generation fails
     */
    public abstract void generateData(byte[] buffer, short offset, short length) throws CryptoException;

    /**
     * Generates random bytes into a buffer; replaces {@link #generateData(byte[], short, short)}.
     *
     * @param buffer output buffer
     * @param offset offset into the buffer
     * @param length number of bytes to generate
     * @return the offset just past the generated bytes, that is {@code offset + length}
     * @throws CryptoException with ILLEGAL_VALUE if {@code length} is not positive
     */
    public abstract short nextBytes(byte[] buffer, short offset, short length) throws CryptoException;

    /**
     * Seeds the random data generator.
     *
     * @param buffer seed data buffer
     * @param offset offset into the buffer
     * @param length length of the seed data
     */
    public abstract void setSeed(byte[] buffer, short offset, short length);

    /**
     * Returns the algorithm of this generator.
     *
     * @return one of the {@code ALG_*} constants
     */
    public abstract byte getAlgorithm();

    /**
     * Random generator for a single request; instances come from a platform pool through {@link #open(byte)}
     * and are returned to it with {@link #close()}, so no persistent memory is consumed.
     */
    public static final class OneShot extends RandomData {

        private OneShot() {
        }

        /**
         * Takes an instance for the given algorithm from the platform pool.
         *
         * @param algorithm one of the {@code RandomData.ALG_*} constants
         * @return an open instance
         * @throws CryptoException with NO_SUCH_ALGORITHM if the algorithm is not supported, or ILLEGAL_USE if no
         *                         instance is available
         */
        public static final OneShot open(byte algorithm) throws CryptoException {
            throw new RuntimeException("stub");
        }

        /**
         * Returns this instance to the platform pool; it must not be used afterwards.
         */
        public void close() {
            throw new RuntimeException("stub");
        }

        @Override
        public byte getAlgorithm() {
            throw new RuntimeException("stub");
        }

        @Override
        public void generateData(byte[] buffer, short offset, short length) throws CryptoException {
            throw new RuntimeException("stub");
        }

        @Override
        public short nextBytes(byte[] buffer, short offset, short length) throws CryptoException {
            throw new RuntimeException("stub");
        }

        @Override
        public void setSeed(byte[] buffer, short offset, short length) {
            throw new RuntimeException("stub");
        }
    }
}
